### ISSUE TITLE
MCP: Update to `@bytebase/dbhub@0.2.2`

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-examples#868]
## About

It looks like with recent version 0.2, a few details have changed for the better. Kudos to upstream authors!
However, the update introduces breaking changes that need to be componsated for.

## Details

- The resource `db://tables` is gone, instead there is `db://schemas` now.
- The `generate_sql` and `explain_db` now gained a `schema` parameter.

## Resources
```yaml
- uri: db://schemas
  name: schemas
  description: null
  mimeType: null
  size: null
  annotations: null
```

## Prompts
```yaml
- name: generate_sql
  description: Generate SQL queries from natural language descriptions
  arguments:
  - name: description
    description: Natural language description of the SQL query to generate
    required: true
  - name: schema
    description: Optional database schema to use
    required: false
- name: explain_db
  description: Get explanations about database tables, columns, and structures
  arguments:
  - name: schema
    description: Optional database schema to use
    required: false
  - name: table
    description: Optional specific table to explain
    required: false
```

## Trivia

It looks like our wishes have been picked up by @tianzhou in one way or another per https://github.com/bytebase/dbhub/commit/fe659ae44666a9a8430799e9d956d6ebf804cba6 and https://github.com/bytebase/dbhub/commit/842933eac202f7af81b245c10ff344db1f9d7798. Thanks!

https://github.com/crate/cratedb-examples/blob/da0643b11728955949cb1532d083e35857af9247/framework/mcp/example_dbhub.py#L50-L53
